spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction-demo
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
